AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  (SO8010)

  CloudFormation for RecSys Lambda

Globals:
  Function:
    Timeout: 30
    Runtime: python3.8
    MemorySize: 1024
    Environment:
      Variables:
        botoConfig: '{"user_agent_extra": "AwsSolution/SO8010/0.1.0"}'
        Stage: !Sub "${Stage}"
  Api:
    Cors:
      AllowMethods: "'GET,POST,DELETE,PUT'"
      AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Parameters:
  Stage:
    Type: String
    Default: dev

  Bucket:
    Description: S3 Bucket for RecSys
    Type: String

  S3Prefix:
    Type: String
    Default: sample-data-news

  StepFunName:
    Description: Step Func Name
    Type: String
    Default: "News-OverAllStepFunc"

  NewsOnlineLoaderURL:
    Type: String
    Default: ""

  MovieOnlineLoaderURL:
    Type: String
    Default: ""

  StepFuncAndLambdaRoleName:
    Type: String
    Default: LambdaAndStepFuncsRole


Mappings:
  LoaderConfigMap:
    NewsOnlineLoaderURL:
      dev: adf45c54cf8734c0f9c14f4adfecae86-234454018.ap-southeast-1.elb.amazonaws.com
      demo: a08ee0a80c43b4cf8af229bf3c70c995-1967456171.ap-southeast-1.elb.amazonaws.com
    MovieOnlineLoaderURL:
      dev: a4fb68ded64b0495f90bbaa36c7773cd-1545468192.ap-southeast-1.elb.amazonaws.com
      demo: a30667949998643caa071da69f042c8f-448313425.ap-southeast-1.elb.amazonaws.com

Resources:
  RSOfflineSNS:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "rs-${Stage}-offline-sns"

  PreCheckLabmda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub rs-${Stage}-PreCheckLabmda
      Handler: precheck-lambda.lambda_handler
      Role: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/rs-${Stage}-${StepFuncAndLambdaRoleName}-${AWS::Region}
      CodeUri:
        Bucket: !Ref Bucket
        Key: !Sub "${S3Prefix}/code/lambda/precheck-lambda.zip"

  S3UtilLabmda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub rs-${Stage}-S3UtilLabmda
      Handler: s3-util-lambda.lambda_handler
      Role: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/rs-${Stage}-${StepFuncAndLambdaRoleName}-${AWS::Region}
      CodeUri:
        Bucket: !Ref Bucket
        Key: !Sub ${S3Prefix}/code/lambda/s3-util-lambda.zip
      Timeout: 900

  SNSMessageLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub rs-${Stage}-SNSMessageLambda
      Handler: sns-message-lambda.lambda_handler
      Role: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/rs-${Stage}-${StepFuncAndLambdaRoleName}-${AWS::Region}
      CodeUri:
        Bucket: !Ref Bucket
        Key: !Sub "${S3Prefix}/code/lambda/sns-message-lambda.zip"
      Timeout: 900
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Sub arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:rs-${Stage}-offline-sns
          NEWS_ONLINE_LOADER_URL: !FindInMap [ LoaderConfigMap, NewsOnlineLoaderURL, !Ref Stage ]
          MOVIE_ONLINE_LOADER_URL: !FindInMap [ LoaderConfigMap, MovieOnlineLoaderURL, !Ref Stage ]